TaskManager/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from tasks import views



urlpatterns = [
    path('', include('core.urls')), 
    path('admin/', admin.site.urls,name="admin"),
    path('tasks/', include('tasks.urls')),
    path('users/',include('users.urls')),
    path('api/get_updates', views.get_updates, name='get_updates'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.loading_view, name='loading'),
    path('home/', views.home_view, name='home'),
    path('help/', views.help, name='help'),
]

tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'

urlpatterns = [
    path('create-category/', views.create_category_view, name='create-category'),
    path('create-task/', views.create_task_view, name='create-task'),
    path('category-detail/<int:category_id>/', views.category_detail_view, name='category-detail'),
    path('task-detail/<int:task_id>/', views.task_detail_view, name='task-detail'),
    path('mark-completed/<int:task_id>/', views.mark_task_completed, name='mark-task-completed'),
    path('mark-postponed/<int:task_id>/', views.mark_task_postponed, name='mark-task-postponed'),
    path('edit-task/<int:task_id>/', views.edit_task_view, name='edit-task'),
    path('edit-category/<int:category_id>/', views.edit_category_view, name='edit-category'),
    path('delete-task/<int:task_id>/', views.delete_task_view, name='delete-task'),
    path('delete-category/<int:category_id>/', views.delete_category_view, name='delete-category'),
    path('task-list/',views.task_list_view, name='task-list'),
    path('completed-tasks/',views.completed_tasks, name='completed-tasks'),
    path('postponed-tasks/',views.postponed_tasks, name='postponed-tasks'),
    path('late-tasks/',views.late_tasks, name='late-tasks'),
    path('pending-tasks/',views.pending_tasks, name='pending-tasks'),
    path('api/get_updates/', views.get_updates, name='get-updates'),
    path('calendar/',views.calendar, name='calendar'),
    path('stats/',views.stats, name='stats'),
    path('search/',views.search, name='search'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('profile/',views.profile, name='profile'),
    path('update-profile/',views.update_profile, name='update-profile'),
]

tasks/forms.py
from django import forms
from .models import Category, Task
from users.models import CustomUser
from django.core.exceptions import ValidationError
from datetime import datetime

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'description']


# Define a custom validation function for the due date
class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['category', 'title', 'description', 'due_date', 'due_time', 'status', 'priority', 'attachments', 'reminders']
        
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)  # Get the 'user' parameter
        super(TaskForm, self).__init__(*args, **kwargs)
        if user is not None:
            self.fields['category'].queryset = Category.objects.filter(user=user)

    def clean_due_date(self):
        due_date = self.cleaned_data['due_date']
        today = datetime.now().date()

        # Check if the due date is in the past
        if due_date < today:
            raise ValidationError('Due date cannot be in the past.')

        return due_date

    def clean_due_time(self):
        due_datetime = datetime.combine(self.cleaned_data['due_date'], self.cleaned_data['due_time'])
        due_time = self.cleaned_data['due_time']
        now = datetime.now()
        # Check if the due time is in the past for the current day
        if due_datetime < now:
            raise ValidationError('Due time cannot be in the past.')
        return due_time

    def clean_reminder_datetime(self):
        reminder_datetime = self.cleaned_data['reminders']
        due_datetime = datetime.combine(self.cleaned_data['due_date'], self.cleaned_data['due_time'])

        # Check if the reminder datetime is in the future and after the due datetime
        if reminder_datetime <= due_datetime:
            raise ValidationError('Reminder datetime must be in the future and after the due datetime.')

        return reminder_datetime

    reminders = forms.DateTimeField(
        required=False,
        help_text='Enter the reminder datetime in the format YYYY-MM-DD HH:MM (e.g., 2023-09-13 08:00).',
        widget=forms.DateTimeInput(attrs={'placeholder': 'YYYY-MM-DD HH:MM'}),
    )

        

class EditCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'description']

class EditTaskForm(forms.ModelForm):
    def __init__(self, user, *args, **kwargs):
        super(EditTaskForm, self).__init__(*args, **kwargs)
        self.fields['category'].queryset = Category.objects.filter(user=user)

    class Meta:
        model = Task
        fields = ['category','title', 'description', 'due_date', 'due_time', 'status', 'priority', 'attachments', 'reminders']

class TaskFilterForm(forms.Form):
    STATUS_CHOICES = [
        ('', 'All'),
        ('completed', 'Completed'),
        ('pending', 'Pending'),
        ('postponed', 'Postponed'),
    ]
    PRIORITY_CHOICES = [
        ('', 'All'),
        ('high', 'High Priority'),
        ('medium', 'Medium Priority'),
        ('low', 'Low Priority'),
    ]

    status = forms.ChoiceField(choices=STATUS_CHOICES, required=False)
    priority = forms.ChoiceField(choices=PRIORITY_CHOICES, required=False)
    category = forms.ModelChoiceField(queryset=None, empty_label='All', required=False)

    def __init__(self, user, *args, **kwargs):
        super(TaskFilterForm, self).__init__(*args, **kwargs)
        self.fields['category'].queryset = Category.objects.filter(user=user)

tasks/views.py
from django.db.models import ExpressionWrapper, F, FloatField,Case, IntegerField,When, Value
from django.shortcuts import render, redirect,get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from .models import Category, Task
from .forms import CategoryForm, TaskForm,EditTaskForm,EditCategoryForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .serializers import TaskSerializer, CategoryWithCountsSerializer
from django.core.serializers import serialize
from django.db.models import Q
from datetime import datetime
import json
from django.db.models import Count
from django.db.models.functions import TruncDate

#Creating tasks and categories 

@login_required
def create_category_view(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            category = form.save(commit=False)
            category.user = request.user
            category.save()
            return redirect('tasks:task-list')
    else:
        form = CategoryForm()
    return render(request, 'tasks/create_category.html', {'form': form})

@login_required
def create_task_view(request):
    if request.method == 'POST':
        form = TaskForm(request.POST, request.FILES, user=request.user)
        if form.is_valid():
            task = form.save(commit=False)
            task.user = request.user
            task.save()
            messages.success(request, 'Task created successfully.')
            return redirect('tasks:task-list')

    else:
        form = TaskForm(user=request.user)

    return render(request, 'tasks/create_task.html', {'form': form})


#Details

@login_required
def task_detail_view(request, task_id):
    task = get_object_or_404(Task, id=task_id, user=request.user)
    return render(request, 'tasks/task_detail.html', {'task': task})

@login_required
def category_detail_view(request, category_id):
    category = get_object_or_404(Category, id=category_id, user=request.user)
    completedTasks = category.get__counts()['completed']
    pendingTasks = category.get__counts()['pending']
    lateTasks = category.get__counts()['late']
    postponedTasks = category.get__counts()['postponed']
    context = {
        'category': category,
        'completed_num': completedTasks,
        'pending_num' : pendingTasks,
        'late_num': lateTasks,
        'postponed_num': postponedTasks,
    }
    return render(request, 'tasks/category_details.html',context)


#Edit Tasks and Categories
@login_required
def edit_task_view(request, task_id):
    task = get_object_or_404(Task, id=task_id, user=request.user)
    if request.method == 'POST':
        form = EditTaskForm(request.user, request.POST, request.FILES, instance=task)
        if form.is_valid():
            form.save()
            return redirect('tasks:task-list')
    else:
        form = EditTaskForm(request.user, instance=task)

    return render(request, 'tasks/edit_task.html', {'form': form, 'task': task})

@login_required
def edit_category_view(request,category_id):
    user = request.user
    category = get_object_or_404(Category,id=category_id,user=user)
    if request.method == 'POST':
        form = EditCategoryForm(instance=category , data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('tasks:task-list')
    else:
        form = EditCategoryForm(instance=category)

    return render(request,'tasks/edit_category.html',{'form':form,'category':category})   


#Changing tasks statuses
@login_required
def mark_task_completed(request, task_id):
    task = get_object_or_404(Task, id=task_id, user=request.user)
    old_status = task.status
    task.status = 'completed'
    task.save()
    return JsonResponse({'message': 'Task marked as completed successfully'})

@login_required
def mark_task_postponed(request, task_id):
    task = get_object_or_404(Task, id=task_id, user=request.user)
    old_status = task.status 
    task.status = 'postponed'
    task.save()
    return JsonResponse({'message': 'Task marked as postponed successfully'})


#delete tasks and categories
@login_required
def delete_task_view(request, task_id):
    task = get_object_or_404(Task, id=task_id, user=request.user)
    if request.method == 'POST':
        task.delete()
        return redirect('tasks:task-list')
    return render(request, 'tasks/delete_task.html', {'task': task})

@login_required
def delete_category_view(request, category_id):
    category = get_object_or_404(Category, id=category_id, user=request.user)
    if request.method == 'POST':
        category.delete()
        return redirect('tasks:task-list')
    return render(request, 'tasks/delete_category.html', {'category':category})


#Task/Category list views
@login_required
def task_list_view(request):
    categories = Category.objects.filter(user=request.user)
    tasks = Task.objects.filter(user=request.user)
    return render(request,'tasks/task_list.html',{'categories':categories,'tasks':tasks})


#Calendar
@login_required
def calendar(request):
    tasks = Task.objects.filter(user=request.user)
    event_colors = {
        'completed': '#379C2F',
        'pending': 'rgba(92, 182, 249, 1)',
        'late': 'rgb(251, 118, 118)',
        'postponed': 'rgba(253, 158, 46, 1)',
    }
    events = []
    for task in tasks:
        start_datetime = datetime(
            year=task.date_creation.year,
            month=task.date_creation.month,
            day=task.date_creation.day,
            hour=task.time_creation.hour,
            minute=task.time_creation.minute,
        )
        due_datetime = datetime(
            year=task.due_date.year,
            month=task.due_date.month,
            day=task.due_date.day,
            hour=task.due_time.hour,
            minute=task.due_time.minute,
        )
        event = {
            'id': task.id,  # Unique identifier for the event
            'title': task.title,
            'status': task.status,
            'color': event_colors.get(task.status, ''),  # Set color based on status
            'start': start_datetime.strftime('%Y-%m-%dT%H:%M:%S'),  # Use task creation datetime as start
            'end': due_datetime.strftime('%Y-%m-%dT%H:%M:%S'),  
            'allDay': False,  # Events span a specific time range
            'task_id': task.id,  # Store task ID for eventClick
        }
        events.append(event)

    return render(request, 'tasks/calendar.html', {'events': json.dumps(events)})

#Stats
@login_required
def stats(request):
    #-Get all taska dn categories for the currently logged in user
    categories = Category.objects.filter(user=request.user)
    tasks = Task.objects.filter(user=request.user)

    #Category with most tasks
    Cat_dict = { category.name: category.get_task_count() for category in categories}
    Cat_with_most_tasks = {key: val for key, val in sorted(Cat_dict.items(), key = lambda ele: ele[1], reverse = True)}
    Cat_max_val = max(Cat_with_most_tasks.values())
    Cat_max_key = max(Cat_with_most_tasks,key=Cat_with_most_tasks.get)
    category_with_most_tasks = categories.get(name=Cat_max_key)
    cat_most_id = category_with_most_tasks.id

    #Category and task counts
    category_count = categories.count()
    task_count = tasks.count()

    #Completion counts
    completed_counts = Task.objects.filter(user=request.user, status='completed').count()
    pending_counts = Task.objects.filter(user=request.user, status='pending').count()
    postponed_counts = Task.objects.filter(user=request.user, status='postponed').count()
    late_counts = Task.objects.filter(user=request.user, status='late').count()

    # Fetch daily_completed_tasks_data
    daily_completed_tasks_data = Task.objects.filter(
        status='completed',
        user=request.user
    ).annotate(
        completion_date=TruncDate('due_date')
    ).values('completion_date').annotate(count=Count('id'))
    daily_completed_tasks_data = list(daily_completed_tasks_data)
    # Convert date objects to strings
    for entry in daily_completed_tasks_data:
        entry['completion_date'] = entry['completion_date'].strftime('%Y-%m-%d')
    # Convert the data to a JSON string
    daily_completed_tasks_data_json = json.dumps(daily_completed_tasks_data)
    print(daily_completed_tasks_data_json)

   # Calculate task status distribution
    task_status_distribution = Task.objects.filter(user=request.user).values('status').annotate(count=Count('status'))
    task_status_distribution_data = [{'status': item['status'], 'count': item['count']} for item in task_status_distribution]
    task_status_distribution_json = json.dumps(task_status_distribution_data)

    #Task Priority Distribution Bar Chart:
    priority_distribution = Task.objects.filter(user=request.user).values('priority').annotate(count=Count('id'))
    priority_distribution_json = json.dumps(list(priority_distribution))

    #Category-wise Completion Rate Radar Chart:
    category_distribution_data = Category.objects.annotate(task_count=Count('task')).values('name', 'task_count')
    # Convert the QuerySet to a list of dictionaries
    category_distribution_data = list(category_distribution_data)
    # Convert the data to a JSON string
    category_distribution_json = json.dumps(category_distribution_data)

    #Task Overdue Status Bar Chart:
    task_overdue_data = Task.objects.filter(status='overdue').values('status').annotate(count=Count('id'))
    task_overdue_data = list(task_overdue_data)
    task_overdue_json = json.dumps(task_overdue_data)

    #Task Completion Rate Histogram
    task_completion_rates = Task.objects.filter(user=request.user).annotate(
        completion_rate=ExpressionWrapper(
            Count('id', filter=F('status') == 'completed') * 100.0 / Count('id'), 
            output_field=FloatField()
        )

tasks/templates/tasks/help.html
{% extends 'tasks/tasks_base.html' %}

{% block heelp %}

{% endblock  %}

tasks/templates/tasks/task_detail.html
{% extends 'tasks/tasks_base.html' %}

{% block title %}
    <title>{{ task.title }}</title>
{% endblock %}

{% block task_detail %}
    <a href="{% url 'tasks:task-list' %}" class="tohome"><span class="material-symbols-outlined">arrow_back</span> Back to Home</a>
    <div class="details">
        <h1>Task Details</h1>
        <div class="text">
            <p><strong>Task Category:</strong> {{ task.category }}</p>
            <p><strong>Task Name:</strong> {{ task.title }}</p>
            <p><strong>Description:</strong> {{ task.description }}</p>
            <p><strong>Due Date:</strong> {{ task.due_date }}</p>
            <p><strong>Due time:</strong> {{ task.due_time }}</p>
            <p><strong>Status:</strong> {{ task.status }}</p>
            <p><strong>Remindal Set On:</strong> {{ task.reminders }}</p>
            <p><strong>Priority:</strong> {{ task.priority }}</p>
        </div>
        <div class="check">
            <div class="set-completed">
                <label class="container" id="completed-task" data-task-id="{{ task.id }}" data-task-status="{{ task.status }}">
                    <input type="radio" name="task-action" class="completed-radio" {% if task.status == 'Completed' %}checked{% endif %}>
                    <svg viewBox="0 0 64 64" height="2em" width="2em">
                        <path d="M 0 16 V 56 A 8 8 90 0 0 8 64 H 56 A 8 8 90 0 0 64 56 V 8 A 8 8 90 0 0 56 0 H 8 A 8 8 90 0 0 0 8 V 16 L 32 48 L 64 16 V 8 A 8 8 90 0 0 56 0 H 8 A 8 8 90 0 0 0 8 V 56 A 8 8 90 0 0 8 64 H 56 A 8 8 90 0 0 64 56 V 16" pathLength="575.0541381835938" class="path-c"></path>
                    </svg>
                </label>
                <p>Mark as Completed</p>
            </div>
            <div class="set-postponed">
                <label class="container" id="postponed-task" data-task-id="{{ task.id }}" data-task-status="{{ task.status }}">
                    <input type="radio" name="task-action" class="postponed-radio" {% if task.status == 'Postponed' %}checked{% endif %}>
                    <svg viewBox="0 0 64 64" height="2em" width="2em">
                        <path d="M 0 16 V 56 A 8 8 90 0 0 8 64 H 56 A 8 8 90 0 0 64 56 V 8 A 8 8 90 0 0 56 0 H 8 A 8 8 90 0 0 0 8 V 16 L 32 48 L 64 16 V 8 A 8 8 90 0 0 56 0 H 8 A 8 8 90 0 0 0 8 V 56 A 8 8 90 0 0 8 64 H 56 A 8 8 90 0 0 64 56 V 16" pathLength="575.0541381835938" class="path-p"></path>
                    </svg>
                </label>
                <p>Mark as Postponed</p>
            </div>
        </div>
    </div>
    <div class="others">
        <a href="{% url 'tasks:edit-task' task.id %}"><button type="button" class="Edit">Edit Task</button></a>
        <a href="{% url 'tasks:delete-task' task.id %}"><button type="button" class="Delete">Delete Task</button></a>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
    $(document).ready(function () {
        // Function to mark a task as completed via AJAX
        $(".completed-radio").on("click", function () {
            const task_id = $(this).closest(".container").data("task-id");

            $.ajax({
                type: "POST",
                url: `/tasks/mark-completed/${task_id}/`,
                data: {
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                },
                success: function (data) {
                    // Handle success (e.g., update the UI)
                    alert(data.message);
                },
                error: function (xhr, status, error) {
                    // Handle errors if needed
                    console.error(error);
                },
            });
        });

        // Function to mark a task as postponed via AJAX
        $(".postponed-radio").on("click", function () {
            const task_id = $(this).closest(".container").data("task-id");

            $.ajax({
                type: "POST",
                url: `/tasks/mark-postponed/${task_id}/`,
                data: {
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                },
                success: function (data) {
                    // Handle success (e.g., update the UI)
                    alert(data.message);
                },
                error: function (xhr, status, error) {
                    // Handle errors if needed
                    console.error(error);
                },
            });
        });
    });
    
</script>
{% endblock %}

tasks/templates/tasks/task_search.html
{% extends 'tasks/tasks_base.html' %}

{% block title%}
    <title>Results for {{query}}</title>
{%endblock%}

{% block search %}
<div class="date">
    <h2>Here are the search results for "{{query}}"</h2>
    <p style="padding-bottom:25px;">We found {{Count}} results</p>
</div>
<div>
    <h3 style="margin-top:20px;border-bottom:1px solid #00000064;padding-bottom:19px;">Categories ({{Count_category}})</h3> 
</div>
<div class="categories" style="z-index:-1;padding-bottom:35px;">
    {% for category in category_results %}
        <div class="card">
            <div class="card-head">
                <p><strong>{{ category.name|slice:":18" }}{% if category.name|length > 18 %}...{%endif%}</strong></p>
                <span class="material-symbols-outlined" id="category-menu">
                    more_vert
                </span>
            </div>
            <p class="Description">{{ category.description|slice:":75" }}{% if category.description|length > 75 %}...{% endif %}</p>
            <p class="stats"><strong>Completed : </strong> {{ category.get_completed_task_count }}/{{ category.get_task_count }}</p>
            <a href="{% url 'tasks:category-detail' category.id %}">View</a>
            <p class="card-footer">Created : {{ category.created_at|date:"d F Y \\a\\t H:i" }}</p>
        </div>
    {% endfor %}
</div>
<div>
    <h3 style="margin-top:20px;border-bottom:1px solid #00000064;padding-bottom:19px;">Tasks ({{Count_task}})</h3> 
</div>
<div class="tasks">
    {% for task in task_results %}
        <div class="task {{task.status}}">
            <a href="{% url 'tasks:task-detail' task.id %}">
                <div class="heading">
                    <p class="first">{{ task.title }}</p>
                    <p class="second {{task.priority}}-priority">{{ task.priority }}</p>
                </div>
                <p class="third"><strong>Category : </strong> {{ task.category.name }}</p>
                <p class="fourth"><strong>Start : </strong> {{ task.date_creation|date:"d F Y" }} at {{ task.time_creation|time:"H:i" }}</p>
                <p class="fifth"><strong>Due : </strong> {{ task.due_date|date:"d F Y" }} at {{ task.due_time|date:"H:i" }}</p>
            </a>
        </div>
    {% endfor %}
</div>

{% endblock  %}

tasks/templates/tasks/tasks_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Task Manager Application, the best way for you to remain organized and boost your productivity.">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %}<title>Task Craft</title>{%endblock%}
    {% block head%}{% endblock%}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@2.0.7/css/boxicons.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@100;300;400;700;900&display=swap" rel="stylesheet">
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simplebar/5.3.6/simplebar.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/simplebar/5.3.6/simplebar.min.js"></script>
    <link rel="stylesheet" href={% static 'tasks/css/base.css' %}>
    <link rel="icon" href="{% static 'core/Resources/Task Craft Logo.png' %}" type="image/png" size="64x64">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
</head>

<body>
    <div class="navbar" id="navbar" style="z-index:99999;">
        <div class="toggle">
            <div>
                <i class='bx bx-menu' id="menu-btn"></i>
                <p>Close</p>
            </div>
        </div>
        <div class="links">
            <a href={% url 'tasks:task-list' %} class="active" data-section="summary">
                <i class="material-icons">apps</i>
                <p>Summary</p>
            </a>
            <a href={% url 'tasks:create-category' %} data-section="create-category">
                <i class='material-icons'>library_add</i>
                <p>Create Category</p>
            </a>
            <a href={% url 'tasks:create-task' %} data-section="create-task">
                <i class='material-icons'>assignment_add</i>
                <p>Create Task</p>
            </a>
            <a href={% url 'tasks:calendar' %} data-section="calendar">
                <i class='material-icons'>calendar_month</i>
                <p>Calendar</p>
            </a>
            <a href={% url 'tasks:stats' %} data-section="stats">
                <i class='bx bx-bar-chart-alt-2'></i>
                <p>Stats</p>
            </a>
            <a href={% url 'core:help' %} data-section="help">
                <i class='material-icons'>help</i>
                <p>Help</p>
            </a>
            <a href={% url 'users:profile' %} data-section="profile">
                <i class='material-icons'>person</i>
                <p>Profile</p>
            </a>
        </div>
        <div class="logout">
            <a href={% url 'users:logout' %} data-section="logout">
                <i class='material-icons'>logout</i>
                <p>logout</p>
            </a>
        </div>
    </div>
    <div class="main-content">
        
        <div class="bar-search">
            <div class="magic">
                <i class='bx bx-menu' id="menu-btn"></i>
                <h1 style="display: flex; position: relative; z-index: -1;">Hey, <span style="color: #12229D; transform:translate(5px,3px);">{{ user.first_name }}</span></h1>
            </div>
            <div class="search-container">
                <form method="get" action="{% url 'tasks:search' %}" class="search-container">
                    {% csrf_token %}
                    <input type="text" name="q" placeholder="Search..." class="search-input">
                    <button style="background:none;border:none;cursor:pointer;padding-left:13px;" type="submit" class="search-btn">
                        <i class="fas fa-search"></i>
                    </button>
                </form>
                <span id ="theme-toggle" class="material-symbols-outlined">
                    dark_mode
                </span>
            </div>
        </div>

        <div class="section" id="summary">
            {% block summary%}
            {% endblock %}
        </div>
        <div class="section" id="create-category">
            {% block create-category %}
            {% endblock %}
        </div>
        <div class="section" id="create-task">
            {% block create-task %}
            {% endblock %}
        </div>
        <div class="section" id="calendar">
            {% block calendar %}
            {% endblock %}
        </div>
        <div class="section" id="stats">
            {% block stats %}
            {% endblock %}
        </div>
        <div class="section" id="help">
            {% block help %}
            {% endblock %}
        </div>
        <div class="section" id="profile">
            {% block profile %}
            {% endblock %}
        </div>
        <div class="section" id="logout">
            {% block logout %}
            {% endblock %}
        </div>
        <div class="section" id="detail">
            {% block task_detail %}
            {% endblock %}
            {% block category_detail %}
            {% endblock %}
            {% block edit_category %}
            {% endblock %}
            {% block edit_task %}
            {% endblock %}
            {% block delete_category %}
            {% endblock %}
            {% block delete_task %}
            {% endblock %}
            {% block search %}
            {% endblock %}
            {% block update_profile %}
            {% endblock %}
        </div>
    </div>
    <script src={% static 'tasks/js/base.js' %}></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>