TaskManager/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from tasks import views



urlpatterns = [
    path('', include('core.urls')), 
    path('admin/', admin.site.urls,name="admin"),
    path('tasks/', include('tasks.urls')),
    path('users/',include('users.urls')),
    path('api/get_updates', views.get_updates, name='get_updates'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.loading_view, name='loading'),
    path('home/', views.home_view, name='home'),
    path('help/', views.help, name='help'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('profile/',views.profile, name='profile'),
    path('update-profile/',views.update_profile, name='update-profile'),
]

users/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.utils import timezone

class CustomUserManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, password=None, **extra_fields):
        if not email:
            raise ValueError("The Email field must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, first_name=first_name, last_name=last_name, **extra_fields)
        
        if password:
            user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name, last_name, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, first_name, last_name, password, **extra_fields)

class CustomUser(AbstractBaseUser, PermissionsMixin):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    )
    class Meta:
        verbose_name_plural = "Users"
        
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=60)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    profile_picture = models.ImageField(upload_to='profile_pictures/', blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def __str__(self):
        return self.email

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    gender = forms.ChoiceField(choices=CustomUser.GENDER_CHOICES, widget=forms.RadioSelect)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if CustomUser.objects.filter(email=email).exists():
            raise forms.ValidationError('This email is already in use.')
        return email

    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'email', 'gender', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['gender'].widget = forms.Select(choices=CustomUser.GENDER_CHOICES)

class CustomUserLoginForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'autofocus': True}),
    )
    password = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password'}),
    )

class CustomUserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'email', 'profile_picture']

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomUserLoginForm,CustomUserUpdateForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from django.contrib import messages
from .models import CustomUser
from tasks.models import Category
import time

@never_cache
def register_view(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()  # Save the user object
            # Authenticate the user and log them in
            user = authenticate(email=form.cleaned_data['email'], password=form.cleaned_data['password1'])
            messages.success(request,'Registration succesfull.')
            for category_name in ['Work', 'Sports', 'Diet']:
                Category.objects.create(name=category_name, description=f"This is the default category created for you to manage your {category_name} tasks", user=user)
            login(request, user)
            return redirect('tasks:task-list')  # Redirect to task category page
        else:
            messages.error(request, 'Invalid registration, Checkout email and password')
    else:
        form = CustomUserCreationForm()
    return render(request, 'users/register.html', {'form': form})

@never_cache
def login_view(request):
    if request.method == 'POST':
        form = CustomUserLoginForm(data=request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(request, email=email, password=password)
            if user is not None:
                messages.success(request,'Logged in succesfully.')
                login(request, user)
                return redirect('tasks:task-list')
            else:
                messages.error(request, 'Invalid credentials, Please check email and password')
    else:
        form = CustomUserLoginForm()
    return render(request, 'users/login.html', {'form': form})


@login_required
def logout_view(request):
    logout(request)
    return redirect('core:home')

@login_required
def profile(request):
    return render(request,'users/profile.html')

@login_required
def update_profile(request):
    if request.method == 'POST':
        form = CustomUserUpdateForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('users:profile')
    else:
        form = CustomUserUpdateForm(instance=request.user)
    return render(request, 'users/update_profile.html', {'form': form})

users/templates/users/base_connect.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="Connect to Task Craft">
    <meta name="viewport" content="width=device-width, initial-scale=1"> 
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">  
    <link rel="stylesheet" href="{% static 'users/css/users_style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="icon" href="{% static 'core/Resources/Task Craft Logo.png' %}" type="image/png" size="64x64">
</head>
<body>
    <div class="Form">
        {% block content %}
        {% endblock %}
    </div>
    <script src="{% static 'users/js/users_script.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script>
        // Make any messages disappear after 3 seconds
        jQuery(document).ready(function() {
            setTimeout(function() {
                jQuery("#messages").fadeOut("slow");
            }, 3000);
        });
    </script>
</body>
</html>

users/templates/users/login.html
{% extends 'users/base_connect.html' %}

{% block title %}
Connect
{% endblock %}

{%block head%}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
{%endblock%}

{% block content %}
<form class="input-form w3-animate-right" style="margin-bottom: 40px; font-weight: bold;" method="post">
    <h2 class="registration-title">Login Form</h2>
    {% csrf_token %}
    
    <!-- Email -->
    <div class="form-group">
        <input type="email" class="form-control" placeholder="Email" name="email" required>
        <div class="valid-feedback">Looks good!</div>
        <div class="invalid-feedback">Please provide a valid email.</div>
    </div>
    
    <!-- Password -->
    <div class="form-group">
        <input type="password" class="form-control" placeholder="Password" name="password" required>
    </div>
    
    <!-- Submit Button -->
    <button type="submit" class="submit-button w3-btn">Submit</button>
    
    <!-- Don't have an account -->
    <p class="account-text" style="margin-top: 20px;">Don't have an account yet? <a href="{% url 'users:register' %}">Create one</a></p>

    <!--Messages from django-->
    {% if messages %}
    <div id="messages">
        {% for message in messages %}
        <div class="Alert {% if message.tags %} Alert-{{ message.tags }} {% endif %}">
            <p>{{ message }}</p>
        </div>
        {% endfor %}
    </div>
    {% endif %}
</form>
{% endblock %}

users/templates/users/profile.html
{% extends 'tasks/tasks_base.html' %} {% load static %} {% block profile %}
<h2>Your Profile</h2>
<div class="tiles">
    <div class="profile-pic">
        <div class="pic">
            {% if user.profile_picture %}
            <img src="{{ user.profile_picture.url }}" alt="{{ user.first_name }}'s Profile Picture"> {% else %}
            <img src="{% static 'users/Resources/default.png' %}" alt="Default Profile Picture"> {% endif %}
        </div>
        <a href={% url 'users:update-profile' %}>
            <div class="pic-edit">
                <span class="material-symbols-outlined">
                    edit
                </span>
            </div>
        </a>
    </div>
    <div class="User-details">
        <p><strong>First Name:</strong> {{ user.first_name }}</p>
        <p><strong>Last Name:</strong> {{ user.last_name }}</p>
        <p><strong>Gender:</strong> {{ user.gender }}</p>
        <p><strong>Email:</strong> {{ user.email }}</p>
        <p style="font-size: 16px; margin-top:15px;">Joined since {{ user.date_joined }}</p>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'users/base_connect.html' %}

{% block title%}
Registration
{%endblock%}

{%block head%}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
{%endblock%}

{% block content %}
<form class="input-form w3-animate-left" style="margin-bottom:40px;font-weight:bold;" method="post">
    <h2 class="registration-title">Registration Form</h2>
    {% csrf_token %}
    
    <!-- First Name -->
    <div class="form-group">
        <input type="text" class="form-control" placeholder="First name" name="{{ form.first_name.name }}" required>
        <div class="valid-feedback">Looks good!</div>
        <div class="invalid-feedback">Please provide a valid first name.</div>
    </div>
    
    <!-- Last Name -->
    <div class="form-group">
        <input type="text" class="form-control" placeholder="Last name" name="{{ form.last_name.name }}" required>
        <div class="valid-feedback">Looks good!</div>
        <div class="invalid-feedback">Please provide a valid last name.</div>
    </div>
    
    <!-- Email -->
    <div class="form-group">
        <input type="email" class="form-control" placeholder="Email" name="{{ form.email.name }}" required>
        <div class="valid-feedback">Looks good!</div>
        <div class="invalid-feedback">Please provide a valid email.</div>
    </div>
    
    <!-- Gender -->
    <div class="form-group">
        <select class="form-control" id="gender" name="gender" required>
            <option value="" selected disabled>Select your gender</option>
            <option value="M">Male</option>
            <option value="F">Female</option>
            <option value="O">Other</option>
        </select>
        <div class="valid-feedback">Looks good!</div>
        <div class="invalid-feedback">Please select your gender.</div>
    </div>
    
    <!-- Passwords -->
    <div class="form-group">
        <input type="password" class="form-control" id="id_password1" placeholder="Password" name="{{ form.password1.name }}" required>
        <div class="valid-feedback">Password meets the requirements.</div>
        <div class="invalid-feedback">Password must be at least 8 characters long and different from other details.</div>
    </div>
    <div class="form-group">
        <input type="password" class="form-control" id="id_password2" placeholder="Confirm Password" name="{{ form.password2.name }}" required>
        <div class="valid-feedback">Passwords match!</div>
        <div class="invalid-feedback">Passwords do not match.</div>
    </div>
    
    <!-- Submit Button -->
    <button type="submit" class="submit-button w3-btn">Submit</button>
    
    <!-- Already have an account -->
    <p class="account-text" style="margin-top:20px;">Already have an account? <a href={% url 'users:login' %}>Login here instead</a></p>

    <!--Messages from django-->
    {% if messages %}
    <div id="messages">
        {% for message in messages %}
        <div class="Alert {% if message.tags %} Alert-{{ message.tags }} {% endif %}">
            <p>{{ message }}</p>
        </div>
        {% endfor %}
    </div>
    {% endif %}

</form>
{% endblock %}

users/templates/users/update_profile.html
{% extends 'tasks/tasks_base.html' %} 
{% load static %} 
{% block update_profile %}
<form method="post" enctype="multipart/form-data">
    <h2>Edit Profile</h2>
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Save</button>
</form>
{% endblock %}